apiVersion: ws.cpd.ibm.com/v1beta1
kind: WS
metadata:
  name: ws-cr     # This is the recommended name, but you can change it
  namespace: cpd-instance     # Replace with the project where you will install Watson Studio
spec:
  license:
    accept: true
    license: Enterprise     # Specify the license you purchased
  version: 4.0.6
  storageVendor: ocs          #if you use a different storage class, replace it with the appropriate storage class                   
